CREATE TABLE "GCG_4273_FURNACE_RPT"(
"BIRUNID" BIGINT,
"JOB" CHAR(6),
"SUFFIX" CHAR(3),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "FURNACE" CHAR(6),
 "TRAYS_PER_FULL_LOAD" NUMERIC(12,4),
 "FURNACE_DATE" DATE,
 "DATE_DUE" DATE,
 "QTY_ORDER" NUMERIC(12,4),
 "NUM_TRAYS" NUMERIC(12,4),
 "FURNACE_LOAD" NUMERIC(12,4),  
 "MOLD" NUMERIC(12,4),
 "DEBIND" NUMERIC(12,4),
"SETTING" NUMERIC(12,4),
 "INT_SECONDARIES" NUMERIC(12,4),
 "EXT_SECONDARIES" NUMERIC(12,4),
"TOTAL_HOURS" NUMERIC(12,4),
"TOTAL_DAYS" NUMERIC(12,4)
);


