CREATE TABLE "GCG_4273_FURNACE_MNT"(
 "FURNACE" CHAR(6),
 "SETTING_HOURS" NUMERIC(12,2),
 "DOWN_TIME" NUMERIC(12,4),
 "TRAYS_PER_FULL_LOAD" NUMERIC(12,4),
 "RUNS_BEFORE_MAINT" NUMERIC(12,4),
 "MAINT_HOURS" NUMERIC(12,4),
 "FURNACE_TIME" NUMERIC(12,2));

